name: astro-component
version: 1
description: Workflow for creating Astro components

specs:
  - openspec/specs/astro-conventions/spec.md#components
  - openspec/specs/styling/spec.md

artifacts:
  - id: spec
    generates: spec.md
    description: Component specification (props, behavior, accessibility)
    template: spec.md

  - id: implementation
    generates: tasks.md
    description: Implementation checklist
    template: tasks.md
    requires: [spec]
    instruction: |
      Files to create:
      - src/components/<Name>.astro
      - src/components/<Name>.module.css

      Verification:
      - Build passes
      - Accessibility checked
      - Visual review

apply:
  requires: [implementation]
  tracks: tasks.md
