name: astro-project
version: 1
description: Master schema for Astro project setup and migration

specs:
  - openspec/specs/astro-conventions/spec.md
  - openspec/specs/styling/spec.md

artifacts:
  - id: vision
    generates: vision.md
    description: Project vision and goals
    template: vision.md

  - id: architecture
    generates: architecture.md
    description: Technical architecture decisions
    template: architecture.md
    requires: [vision]

  - id: migration-plan
    generates: migration-plan.md
    description: Step-by-step migration tasks
    template: migration-plan.md
    requires: [architecture]

  - id: ai-workflow
    generates: ai-workflow.md
    description: AI agent architecture (optional)
    template: ai-workflow.md
    requires: [architecture]

  - id: verification
    generates: verification.md
    description: Final verification checklist
    template: verification.md
    requires: [migration-plan]

apply:
  requires: [migration-plan]
  tracks: migration-plan.md
